//! Seifert–van Kampen theorem: compute fundamental group by gluing agent subspaces.

use serde::{Deserialize, Serialize};
use crate::policy::Policy;
use crate::fundamental_group::GroupWord;

/// A subspace with its own fundamental group.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Subspace {
    /// Name of the subspace.
    pub name: String,
    /// Sample points in the subspace.
    pub points: Vec<Policy>,
    /// Fundamental group rank (number of generators).
    pub fundamental_group_rank: usize,
}

impl Subspace {
    pub fn new(name: impl Into<String>, points: Vec<Policy>, rank: usize) -> Self {
        Self { name: name.into(), points, fundamental_group_rank: rank }
    }
}

/// The Seifert–van Kampen theorem computes π₁(X) = π₁(U ∪ V)
/// from π₁(U), π₁(V), and π₁(U ∩ V) together with inclusion maps.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SeifertVanKampen {
    /// First subspace U.
    pub u: Subspace,
    /// Second subspace V.
    pub v: Subspace,
    /// Intersection U ∩ V.
    pub intersection: Subspace,
}

impl SeifertVanKampen {
    /// Create a new van Kampen decomposition.
    pub fn new(u: Subspace, v: Subspace, intersection: Subspace) -> Self {
        Self { u, v, intersection }
    }

    /// Compute the fundamental group of U ∪ V.
    /// π₁(U ∪ V) = π₁(U) * π₁(V) / N
    /// where N is the normal subgroup generated by i₁(g)·i₂(g)⁻¹ for g ∈ π₁(U ∩ V).
    pub fn compute_fundamental_group(&self) -> VanKampenResult {
        let rank_u = self.u.fundamental_group_rank;
        let rank_v = self.v.fundamental_group_rank;
        let rank_intersection = self.intersection.fundamental_group_rank;

        // Free product rank = rank_U + rank_V
        let free_product_rank = rank_u + rank_v;

        // Relations from the intersection: each generator of π₁(U ∩ V)
        // produces a relation identifying its images in U and V.
        let num_relations = rank_intersection;

        // The fundamental group rank (simplified)
        let result_rank = if free_product_rank >= num_relations {
            free_product_rank - num_relations
        } else {
            0
        };

        VanKampenResult {
            free_product_rank,
            num_relations,
            result_rank,
            description: format!(
                "π₁({} ∪ {}) = <gen_U_{} * gen_V_{}> / {} relations from intersection",
                self.u.name, self.v.name, rank_u, rank_v, num_relations
            ),
        }
    }

    /// Check if the union is simply connected.
    pub fn is_simply_connected(&self) -> bool {
        self.compute_fundamental_group().result_rank == 0
    }

    /// Compute the amalgamated free product with explicit generators.
    pub fn amalgamated_product(&self) -> AmalgamatedProduct {
        let u_gen: Vec<String> = (0..self.u.fundamental_group_rank)
            .map(|i| format!("u_{}", i))
            .collect();
        let v_gen: Vec<String> = (0..self.v.fundamental_group_rank)
            .map(|i| format!("v_{}", i))
            .collect();
        let relations: Vec<GroupWord> = (0..self.intersection.fundamental_group_rank)
            .map(|i| {
                // i₁(g_i) * i₂(g_i)⁻¹
                GroupWord {
                    letters: vec![
                        (i.min(rank_from(self.u.fundamental_group_rank) - 1), 1),
                        (self.u.fundamental_group_rank + i.min(rank_from(self.v.fundamental_group_rank) - 1), -1),
                    ],
                    group_generators: self.u.fundamental_group_rank + self.v.fundamental_group_rank,
                }
            })
            .collect();

        AmalgamatedProduct {
            u_generators: u_gen,
            v_generators: v_gen,
            relations,
        }
    }
}

fn rank_from(r: usize) -> usize {
    if r == 0 { 1 } else { r }
}

/// Result of a van Kampen computation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VanKampenResult {
    /// Rank of the free product π₁(U) * π₁(V).
    pub free_product_rank: usize,
    /// Number of relations from the intersection.
    pub num_relations: usize,
    /// Estimated rank of π₁(U ∪ V).
    pub result_rank: usize,
    /// Human-readable description.
    pub description: String,
}

/// An amalgamated free product with explicit presentation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AmalgamatedProduct {
    /// Generators from U.
    pub u_generators: Vec<String>,
    /// Generators from V.
    pub v_generators: Vec<String>,
    /// Relations from the amalgamation.
    pub relations: Vec<GroupWord>,
}

impl AmalgamatedProduct {
    /// Total number of generators.
    pub fn total_generators(&self) -> usize {
        self.u_generators.len() + self.v_generators.len()
    }

    /// Number of relations.
    pub fn num_relations(&self) -> usize {
        self.relations.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fundamental_group::FreeGroup;

    fn make_base_policy() -> Policy {
        Policy::new(vec![0.0, 0.0])
    }

    #[test]
    fn test_van_kampen_creation() {
        let u = Subspace::new("U", vec![make_base_policy()], 1);
        let v = Subspace::new("V", vec![make_base_policy()], 1);
        let inter = Subspace::new("U∩V", vec![make_base_policy()], 0);
        let vk = SeifertVanKampen::new(u, v, inter);
        assert_eq!(vk.u.name, "U");
    }

    #[test]
    fn test_simple_union() {
        // Two contractible spaces overlapping → union is contractible
        let u = Subspace::new("U", vec![make_base_policy()], 0);
        let v = Subspace::new("V", vec![make_base_policy()], 0);
        let inter = Subspace::new("U∩V", vec![make_base_policy()], 0);
        let vk = SeifertVanKampen::new(u, v, inter);
        assert!(vk.is_simply_connected());
    }

    #[test]
    fn test_circles_glued() {
        // Two circles glued at a point → figure-eight (rank 2)
        let u = Subspace::new("circle_1", vec![make_base_policy()], 1);
        let v = Subspace::new("circle_2", vec![make_base_policy()], 1);
        let inter = Subspace::new("point", vec![make_base_policy()], 0);
        let vk = SeifertVanKampen::new(u, v, inter);
        let result = vk.compute_fundamental_group();
        assert_eq!(result.result_rank, 2);
    }

    #[test]
    fn test_circles_with_intersection() {
        // Two circles overlapping in a circle → single circle (rank 1)
        let u = Subspace::new("U", vec![make_base_policy()], 1);
        let v = Subspace::new("V", vec![make_base_policy()], 1);
        let inter = Subspace::new("U∩V", vec![make_base_policy()], 1);
        let vk = SeifertVanKampen::new(u, v, inter);
        let result = vk.compute_fundamental_group();
        assert_eq!(result.result_rank, 1);
    }

    #[test]
    fn test_amalgamated_product() {
        let u = Subspace::new("U", vec![make_base_policy()], 1);
        let v = Subspace::new("V", vec![make_base_policy()], 1);
        let inter = Subspace::new("U∩V", vec![make_base_policy()], 1);
        let vk = SeifertVanKampen::new(u, v, inter);
        let prod = vk.amalgamated_product();
        assert_eq!(prod.total_generators(), 2);
        assert_eq!(prod.num_relations(), 1);
    }

    #[test]
    fn test_van_kampen_result_description() {
        let u = Subspace::new("U", vec![make_base_policy()], 2);
        let v = Subspace::new("V", vec![make_base_policy()], 3);
        let inter = Subspace::new("U∩V", vec![make_base_policy()], 1);
        let vk = SeifertVanKampen::new(u, v, inter);
        let result = vk.compute_fundamental_group();
        assert!(!result.description.is_empty());
        assert_eq!(result.free_product_rank, 5);
        assert_eq!(result.num_relations, 1);
        assert_eq!(result.result_rank, 4);
    }

    #[test]
    fn test_trivial_subspaces() {
        let u = Subspace::new("U", vec![], 0);
        let v = Subspace::new("V", vec![], 0);
        let inter = Subspace::new("U∩V", vec![], 0);
        let vk = SeifertVanKampen::new(u, v, inter);
        assert!(vk.is_simply_connected());
    }

    #[test]
    fn test_free_group_operations() {
        let fg = FreeGroup::new(2);
        // aba⁻¹b⁻¹ is not the identity in the free group
        let word = fg.word(vec![(0, 1), (1, 1), (0, -1), (1, -1)]);
        // In the free group, this is NOT the identity (it's a relation)
        // But our reduction only cancels adjacent inverses
        assert!(!fg.is_identity(&word));
    }

    #[test]
    fn test_higher_rank() {
        let u = Subspace::new("torus_half", vec![make_base_policy()], 2);
        let v = Subspace::new("other_half", vec![make_base_policy()], 2);
        let inter = Subspace::new("intersection", vec![make_base_policy()], 1);
        let vk = SeifertVanKampen::new(u, v, inter);
        let result = vk.compute_fundamental_group();
        assert_eq!(result.free_product_rank, 4);
        assert_eq!(result.result_rank, 3);
    }

    #[test]
    fn test_amalgamated_product_generators() {
        let u = Subspace::new("U", vec![make_base_policy()], 3);
        let v = Subspace::new("V", vec![make_base_policy()], 2);
        let inter = Subspace::new("U∩V", vec![make_base_policy()], 2);
        let vk = SeifertVanKampen::new(u, v, inter);
        let prod = vk.amalgamated_product();
        assert_eq!(prod.u_generators.len(), 3);
        assert_eq!(prod.v_generators.len(), 2);
        assert_eq!(prod.relations.len(), 2);
    }
}
